### ISSUE TITLE
Add an optional "This task will save us .. euro" field

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#102]
## Problem that this feature solves

If a task has a field that describes how much money we save by getting the task done, it can motivate people to help us.

## Feature description

I saw this on the patagonia.catchafire.org volunteer platform. Their tasks have a field that explains how much money it saves the organisation if someone were to take on that task. This can motivate people, as instead of donating for example 50 euros, they can see that they can be way more valuable when donating their skill and save us 500 euros. 

I don't know if we should include something like this, but I thought it is an interesting idea as I think it can really make people understand the value of their skills and time.

Example from a [web design task](https://patagonia.catchafire.org/volunteer/49168/human-impacts-institute--website-visual-design/):

![image](https://user-images.githubusercontent.com/51111316/97918706-d3a30000-1d56-11eb-850e-bc02bf25c43e.png)

**Comment by SamLubbers** [comment]
Thanks for the suggestion Kaj! In some cases showing financial rewards can help, but what often happens is that it crowds-out the moral or ethical reasons to do something. So the task becomes about saving some money instead of addressing a humanitarian crisis which is predicted to kill hundreds of millions of people. If you're interested to look more into this idea I highly recommend [this book](https://www.goodreads.com/book/show/13221379-what-money-can-t-buy)

And even if a monetary value could help it would be quite impossible to calculate it for every task and role :sweat_smile:
