### ISSUE TITLE
Multilingual role publishing, editing and viewing

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#103]
## Problem that this feature solves

Roles should be published in both Dutch and English, so that all rebels in XR NL can read about them and apply. Currently it's only possible to post the roles in one language.

### Role creation and editing

When a rebel publishes a new role they should provide these fields in both Dutch and English:
* Title
* Responsibilities
* Description
* Requirements

All other fields can be automatically translated through string translation. To start we'll just keep it simple and add all fields to one form, so we'll have first description (Dutch) and then description (English), and so for all the fields. This format also makes it easy to edit the roles in different languages.

On submit, the dutch and english text is then stored in the roles table of the database.

Rebels should also be able to mark a role as only relevant for dutch or english speakers, which would then make the fields of the other language not-required.

In the future we can improve this by only requiring information in one language, and when users click submit, they are shown a set of fields to be translated. What would make this even easier for users if we already automatically translated everything using DeepL, and they just need to adjust the translated text.

#### Roles overview

When user are on the Dutch version of the page, they see all roles with the dutch text. Same for the english version of the page. If a role does only have a dutch version, it shouldn't appear on the english version of the page, and vice versa.

### Individual role view

A last edge case to consider is if a user is in the english version of the page, and go to a URL corresponding to a role that is only in Dutch. In such cases the role view should display a text saying that this role is only available in dutch, along with a button to go to the dutch version of the page. For this you can reuse the functionality for when a role is already taken.

**Comment by SamLubbers** [comment]
I'll share here the initial design that @kajdehoop made

<img width="1440" alt="New Role Modal" src="https://user-images.githubusercontent.com/15846595/105965472-be065380-6083-11eb-81e0-33081847f8ee.png">

And here is the feedback that I already shared in the channel:

> this new design is nice, especially because it is more compact and it doesn't require translations for things like phone number, working circle... 
> I think it can be even better if the translations for each field are together. So first you fill in the role description in Dutch and then in English. That way you can write some text, copy it to an online translator and directly paste it in the next field. 

@aleesaan you had similar feedback right? Do you have some insights/sketches on how you do translations in your company?

**Comment by aleesaan** [comment]
Yes, here it is!

https://user-images.githubusercontent.com/42735629/106031038-0d25a600-60cf-11eb-85e7-764859c3a6d7.mov

I think something along these lines would be good.

**Comment by kajdehoop** [comment]
Cool, I'll see if I can design our role modal like that :) I've discovered that Adobe XD is free, so today I've been figuring out how it all works and it works better than Figma

**Comment by kajdehoop** [comment]
@aleesaan @SamLubbers 

I've redesigned the New Role modal so it's doing the translations the way you recommended :) I also improved the layout and added some icons. I added a switch for internal/external (public) role, so people are able to mark a role as 'internal' so they can be viewed only by existing members of XR. I also added a field for the Github links that can be filled in for tech roles. Below the contact info there's a warning that the contact info will be publicly shown on the website so people won't accidentally make their phone number public.  

![image](https://user-images.githubusercontent.com/51111316/106298754-961a1a00-6254-11eb-995d-fbaa62243800.png)

**Comment by aleesaan** [comment]
Thanks for the designs @kajdehoop!! I really like the new layout with grouped fields, and also the text at the end!  
Regarding the extra fields you added, I think it's best to leave them for a separate PR since they're out of the scope of this one - but I get that you designed the whole form so thanks again :)  
The only thing I'm not sure about is the multi-language fields sharing borders, don't you think it might be a bit too much when we will have more than two languages? I'd keep a small gap between them, like you did in the other inputs. What do you think?

**Comment by kajdehoop** [comment]
@aleesaan I'm happy that you like the design :) I think I'll have some time tonight to review the design of those input fields, got an idea for improving them already 👍

**Comment by kajdehoop** [comment]
@aleesaan I've updated the design🙂 The fields now have a small gap with the titles above the fields instead of in the placeholder (to make it clear that they are connected to each other). The flags have been moved to the left and the translation fields are always expanded. I've decided to do that because this makes the interaction more clear and we want to encourage people to fill in both languages. If we ever add more languages, we can make it in a dropdown-like style to free up space, but for now this is most clear and we only have 4 translatable fields so we have the room for it.

![image](https://user-images.githubusercontent.com/51111316/106489453-15a62400-64b5-11eb-976f-0241ad1b9f16.png)

**Comment by SamLubbers** [comment]
@kajdehoop thank you so much for making the new designs. They already look great! I heard from Ale that you've been discussing the design further. Here are some additional points of feedback (in case you don't have them yet):

- I agree with Ale for leaving the additional fields for separate issues. We already have issue #128 for internal/external roles. As for the Github link this will be used so rarely that I think we can remove it and add the link in the role description
- If people see other roles in the website they'll see that all info will be publicly available. What's the rationale for adding the message at the end? Do you think people might fear having their contact details disclosed?
- It might not be entirely clear what is asked in each field when the label is on top and each field just has a flag. I think it would be better to have a field description + flag in each field. Just like we have in the [current form for the website](https://docs.google.com/forms/d/e/1FAIpQLSdIabp3sec0mgTClLctp4VPxjsaghAK6e_PyTlwrxM4i2eWug/viewform). 
- In terms of how this can be displayed, I think we can continue using the native vuetify floating labels, rather than the label above the field. 
- Use :gb: flag instead of :us: And maybe to be more explicit, we mention in which language the role must be completed. So instead of "title :gb:" we could have "title (in english :gb:)" 
- On top of the new role dialogue I would add a short description that all roles should be completed in both dutch and english so that everyone in the movement can apply for them.
- For Dutch only roles, what do you think we should do?
  - easy option: tell people to mention in the english fields that the field is for dutch speakers only / don't mention it and let people figure it out (as they've been doing so far)
  - advanced option: have a toggle for selecting whether the roles are dutch only. Based on that the fields are/are not shown. I believe that this adds too much complexity at this point.
- add a cancel button next to submit (just like in the existing form :ok_hand:  )

**Comment by aleesaan** [comment]
> * I agree with Ale for leaving the additional fields for separate issues. We already have issue #128 for internal/external roles. As for the Github link this will be used so rarely that I think we can remove it and add the link in the role description

I agree about the link!  

> * It might not be entirely clear what is asked in each field when the label is on top and each field just has a flag. I think it would be better to have a field description + flag in each field. Just like we have in the [current form for the website](https://docs.google.com/forms/d/e/1FAIpQLSdIabp3sec0mgTClLctp4VPxjsaghAK6e_PyTlwrxM4i2eWug/viewform).
> * In terms of how this can be displayed, I think we can continue using the native vuetify floating labels, rather than the label above the field.
> * Use 🇬🇧 flag instead of 🇺🇸 And maybe to be more explicit, we mention in which language the role must be completed. So instead of "title 🇬🇧" we could have "title (in english 🇬🇧)"

I agree about the British flag! As for the fields labels, indeed it's been the main point of our discussions (off-github). Kaj will share some new designs about this soon, but we're thinking to have the label grouping the fields, and then in each field have "🇬🇧 English". This way we don't have to repeat the label every time. Your suggestion might also be good though, having the label plus flag. @kajdehoop maybe you can give a try to both ideas so we can compare? If it's not too complicated 😇 

> * On top of the new role dialogue I would add a short description that all roles should be completed in both dutch and english so that everyone in the movement can apply for them.

I think it's good to mention this as a recommendation rather than a requirement. Then, when filling the fields - if they're required - we can show an error saying that at least one language needs to be filled.

> * For Dutch only roles, what do you think we should do?
>   
>   * easy option: tell people to mention in the english fields that the field is for dutch speakers only / don't mention it and let people figure it out (as they've been doing so far)
>   * advanced option: have a toggle for selecting whether the roles are dutch only. Based on that the fields are/are not shown. I believe that this adds too much complexity at this point.

Yea that would require adding a new field to the Role model, and then a filter to allow filtering based on that. We could do it (in a separate case) if we see it's needed, but for now I think it's enough to mention it in the title/description/requirements/whatever. Plus, just the fact that a role doesn't have English translations could be already a good indicator that if you don't know Dutch you shouldn't apply.

> * add a cancel button next to submit (just like in the existing form 👌  )

Yep!
