### ISSUE TITLE
Clear filters button should only be available when filters are applied

### ISSUE THREAD

**Issue by aleesaan** [xrnl/aginun#149]
## Steps to reproduce the problem
We currently show the "Clear filters" button all the time, but it would be nice if we disabled / hid it when no filters are applied.

## Expected result after following these steps
The button becomes active / visible once at least once filter has been applied.

**Comment by rijusougata13** [comment]
hey can you guide me from which file i can start with?

**Comment by SamLubbers** [comment]
@rijusougata13 great that you want to help out :smile: the file with the button is `src/views/RolesOverview.vue`

The way to easily find any other button is to do a project wide search with the button text :ok_hand:

**Comment by SamLubbers** [comment]
I think it's best if the button is disabled, instead of hidden, so that the user interface is more predictable for the user.

Additionally, it would be good to have a [tooltip](https://v2.vuetifyjs.com/en/components/tooltips/) that tells the user "no filters are selected" when the button is disabled. The tooltip shouldn't be shown when the button is enabled.
