### ISSUE TITLE
Implement design: Support page

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#172]
Change current Support page to match new Support page design 

[Link to design](https://zeroheight.com/4eba4d3a1/p/60c9ec-support/b/407259)

[Link to illustrations used in the design](https://zeroheight.com/4eba4d3a1/p/80374f-illustrations)

**Comment by aleesaan** [comment]
Implemented in my [last commit](https://github.com/xrnl/aginun/commit/486a3b443add8cbe2f31226fa7175ebcfc72f5e6).

**Comment by SamLubbers** [comment]
@aleesaan looks amazing :heart_eyes: 

@kajdehoop I see that the contact email in the designs is the XR welcome email and not the tech email. This is useful if people have questions about getting involved in XR, but not if they have questions about the platform because we don't have access to that email. I suggest adapting the text so that the first option is for technical questions & suggestions about the platform, and the second contact option is to learn about more ways to get involved in XR.
