### ISSUE TITLE
Implement design: Navbar

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#174]
[Link to design](https://zeroheight.com/4eba4d3a1/p/5611c9-navbar/b/0329b7)

**Comment by aleesaan** [comment]
Hey @kajdehoop, thanks for creating this and all the other designs issues! After my [last commit](https://github.com/xrnl/aginun/commit/56823b92924aed88e76c7768b63ed22420c0d1aa) the navbar looks like this on desktop:  

![image](https://user-images.githubusercontent.com/42735629/120923710-39ca7980-c6d0-11eb-8773-42a8b89e6362.png)

and on mobile:  

![image](https://user-images.githubusercontent.com/42735629/120923719-48b12c00-c6d0-11eb-9401-c916a7652b21.png)
![image](https://user-images.githubusercontent.com/42735629/120923759-7c8c5180-c6d0-11eb-8f9e-a824819fc862.png)

The mobile menu is slightly different but making it exaclty the same would require quite a few extra work. If you're ok with it I'd suggest to keep this like this for now so we can focus on finishing up the rest of the designs and ship the first version.  
  
As a more general point, I think it would be good to do these little compromises for now: instead of spending an hour fixing styles to make something slightly better - and since we'll have to rewrite all the styles when we migrate to Bootstrap after the [next version](https://github.com/xrnl/aginun/wiki/Roadmap#next-version) - it's better to spend an hour improving another part of the app that doesn't look at all like the designs / doesn't exist yet. I'd focus on getting the app as close as we can to the designs, and then finalize them after we migrate to Bootstrap, to optimize the process. What do you think?

**Comment by SamLubbers** [comment]
@aleesaan agreed! Let's first spend the least effort we can to obtain the greatest design changes. One consequence of this method is that we'll end up with a lot of issues that are partly implemented. In such cases I suggest listing at the bottom of the issue the last things that need to be implemented. In this case that is:

- [ ] make language menu a consistent design with the rest of the navbar
- [ ] show mobile menu below navbar & align items from top to bottom (instead of being centered)

**Comment by kajdehoop** [comment]
Yes good idea! Let's go for a speedy implementation, list all the things that need to be done later beneath the issues and then do another iteration when the first round is done ⚡

**Comment by aleesaan** [comment]
Closed in #224.
