### ISSUE TITLE
Fix apollo caching

### ISSUE THREAD

**Issue by SamLubbers** [xrnl/aginun#178]
## Steps to reproduce the problem

1. apply a filter that shows a subset of roles. For example, type something in the search field. 
2. delete one of the role
3. remove filter(s)

## Expected result after following these steps

The role that we've deleted doesn't show anymore

## Actual result

The role that we've delete appears again after removing filters.

## Additional comments

This error occurs because Apollo has caching enabled. The first time you load all roles is stores the result for that query in a cache. After you delete the role, and then make the same query as the first time, it doesn't get all the roles from the backend, but instead gets the roles from the cached result of the query. To fix this we can either:

1. Remove apollo caching completely, and use the Vuex store as the single source of truth
2. Refresh the apollo cache every time a role is created/edited/deleted.

**Comment by jurcello** [comment]
This happens in the same tab right? I mean, the issue is not that when a role is removed all other active clients might still have the role in cache (either in apollo cache or in the vuex store).

As we are using a vuex store, I would say we should remove the apollo cache. An extra network request is not a big problem, especially if hasura has an efficient caching mechanism.

**Comment by SamLubbers** [comment]
@jurcello indeed! this occurs on the same tab. I agree with you that removing the apollo cache is the best solution, especially because all it's caching is automatic and therefore unpredictable. It's better to use the Vuex store so that we know exactly what is or is not stored in local memory. Thanks for already making a pull request that solves this :raised_hands:
