### ISSUE TITLE
Role info modal: Remove ‘role filled’ button when logged in

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#195]

**Comment by SamLubbers** [comment]
since this is a design improvement, let's do it after the next version. 

One thing: I think we should remove "role filled" as it doesn't clearly indicate what will happen if you click it, and also people often leave roles online even after they are filled so that they can find more people. Instead, I would have an archive button on the top right (replacing the delete button). Then, once you archive, you can delete the card (just like in Trello)

**Comment by SamLubbers** [comment]
@kajdehoop thanks for chipping in :smile: I'll reply in the other issue as that's where the main discussion is going on about the consistent view.
