### ISSUE TITLE
Role info modal: Remove edit/delete dots in top right when logged in

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#196]

**Comment by aleesaan** [comment]
We should still keep those buttons for your own cards though, right?

**Comment by kajdehoop** [comment]
No, this will now be done through the My Roles page so they don't clutter the overview and there's just 1 clear way to edit/delete cards

**Comment by aleesaan** [comment]
Mmh I think that would be quite confusing for users, cause the view role modal will be the same in both `/my-roles` and in `/roles`. So if I open the same role (published my myself) in `/my-roles` and in the `/roles` page, it would be confusing for me to see the edit/delete option only when I'm in the `/my-roles`...
  
I don't think it clutters the UI anyway - you'd only see it for the roles you published, and it looks quite nice now:

https://user-images.githubusercontent.com/42735629/141496333-6b82ce92-c774-4c94-978a-5fcf0faf41b5.mov

**Comment by SamLubbers** [comment]
Consistency is indeed one of the most important things in a design, but I'm not sure if it's most consistent to always have your role cards with buttons to edit and delete, or to only be able to edit and delete through the my roles page :thinking: I'll add it to the agenda for a future meeting so that we can talk about it. And @kajdehoop this would also be a good one to include in the list of user testing questions!
