### ISSUE TITLE
Change the arrow on the filtering slide-out  in the mobile site

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#95]
## Problem that this feature solves
The 'back' arrow on the filtering slide-out sidebar in the mobile website feels as if it's the wrong way around. The arrow points to the left, which seems logical at first as it takes you back. But when the slide-out closes, it animates to the right, as if it's on top of the page and moves out of the way.

## Feature description
If we flip the arrow (point it to the right) it will probably feel more logical, because then it's in line with the direction of animation

**Comment by SamLubbers** [comment]
@kajdehoop it points to the left because in web applications a left arrows symbolizes "go back to where I came from", which is precisely what happens when you close a filter. As you can see, the [google jobs page](https://careers.google.com/jobs/results/?company=Google&company=Google%20Fiber&company=YouTube&employment_type=FULL_TIME&hl=en_US&jlo=en_US&q=software&sort_by=relevance#modal_open) works the same :innocent:

**Comment by kajdehoop** [comment]
That's true, but the animation seems to go the wrong way. Maybe we can flip the animation direction instead of use a cross instead of an arrow. But this is not the most important issue haha 😜
