### ISSUE TITLE
Add remote field

### ISSUE THREAD

**Issue by kajdehoop** [xrnl/aginun#98]
## Problem that this feature solves
I saw that in the similar platform on XR UK there are roles that have a 'remote' tag, so it's clear to volunteers that they can do this role remotely. This might be handy.In their platform you can also add a meeting time, format and schedule. Maybe we can add this so it’s more clear for new volunteers at what times they can best be available.

## Feature description
Add the fields 'remote' (yes/no), 'meeting time' (Wednesday, 19:00),  'meeting format' (conference call) and 'meeting schedule' (bi-weekly) to a role. 

## Additional comments
Maybe we can look at the current platforms that XR organisations in different countries use to find out which fields are provided in their role offerings. This will make it easier to convince people globally to use our platform in the future.

**Comment by SamLubbers** [comment]
@kajdehoop good suggestion! I think adding the remote field is crucial, especially with COVID-19. 

I would leave meeting details out for now as we want to really promote asynchronous work, and we want to keep the role fields minimal for now so there isn't too much information for volunteers. 

And regarding your last comment, afaik only the UK has a volunteer page. XR Global is already happy to adopt our platform because right now they don't have any kind of volunteer page. Once people start using it in NL and outside we can continue improving the fields in response to feedback.

**Comment by kajdehoop** [comment]
Oh nice! If they don't have a volunteer page yet that makes it easier for us ^^

**Comment by aleesaan** [comment]
Instead of having a "Remote" field as a boolean, what do you guys think of adding a "Tags" field instead? We could then render each tag as a badge in the cards/role view.  
I think this would have two benefits:

- Less info in the main block of text, which would make it easier for the users to read;
- More scalable, as we could add more (boolean) tags as needed.   

To input these tags, it would be nice to have a list of available ones (perhaps in different colors) that you can toggle when creating/editing a role; although, this might be kinda weird if we only have this "Remote" tag (unless you guys have ideas for a couple more?). If not, we can also input them as we do for Responsibilities, but then we'd give freedom to the users to input whatever they want.

**Comment by SamLubbers** [comment]
Hey @aleesaan I think that's a great idea! I think we should just let users choose their own tags, as we can't predict all the tags that people might want to use. For example, people in the XR NL fashion action group might want to make a `fastion` tag so that people interested in taking action against fast fashion can easily find them.

Could you make a separate issue for this feature? So we'll first implement the remote field for this version, and then we'll support for multiple tags in a future verison.

**Comment by SamLubbers** [comment]
Closing this issue as a better alternative is proposed in #116
